#!/usr/bin/php
<?php

include "./index.php";

$commands = require "./configs/command.php";

$flag = false;

foreach ($commands as $c) {
	if ($c::$command == $argv[1]) {
		$c::handle();
		$flag = true;
		break;
	}
}
if (!$flag) {
	die("No command");
}

