#!/usr/bin/php
<?php

include "./index.php";

$commands = require "./configs/command.php";


$objectCommands = [];


foreach ($commands as $c) {
	$oc = new $c();
	$objectCommands[$oc->command] = $oc;
}

if (in_array($argv[1], array_keys($objectCommands))) {
	$objectCommands[$argv[1]]->handle();
}

die("No command");

// var_dump($commands[2]);
